# Allow live config reload
live_config_reload = true

# Bell configuration
[bell]
animation = "EaseOutExpo"
duration = 0

# Colors configuration
[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

# Font configuration
[font]
size = 11

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
family = "Fira Code Nerd Font"




# Cursor configuration
[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

# Environment variables
[env]
TERM = "xterm-256color"

# Mouse configuration
[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# Selection configuration
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# Shell configuration
[shell]
program = "/bin/zsh"

# Window configuration
[window]
decorations = "full"
dynamic_title = true
#startup_mode = "Maximized"

[window.dimensions]
columns = 100
lines = 30

